#Connection url for connection in the DatabaseView:
#  jdbc:mysql://0.0.0.0:13306/DOCKERDB, login=root, password=root
#App is available at: http://localhost:<local-port>/entitybus/post
networks:
  testnetwork:
services:
  java:
    build:
      context: .
      target: corretto22
    container_name: spring-rest-api
    networks:
      - testnetwork
    tty: true
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    build:
      context: .
      target: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/db-init-scripts:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-P",
          "3306",
          "-u",
          "user",
          "--password=password",
          "-e",
          "select 1",
          "shop"
        ]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - testnetwork
