spring:
  application:
    name: atoraku
  datasource:
    url: jdbc:mysql://testdb:3306/CAKE_SHOP
    username: atrk
    password: atrk1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
