spring:
  application:
    name: atoraku
  datasource:
    url: jdbc:mysql://db:3306/shop
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
